version: "3.8"

services:
  configserver:
    container_name: configserver
    image: siferga/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - bankApplication-network

  eurekaserver:
    container_name: eurekaserver
    image: siferga/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - bankApplication-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  ms-Accounts:
    container_name: accounts
    image: siferga/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bankApplication-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  ms-Cards:
    container_name: cards
    image: siferga/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bankApplication-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  ms-Loans:
    container_name: loans
    image: siferga/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bankApplication-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
networks:
  bankApplication-network:
